-- This file has been generated by Dungeon Editor 2.1.7

-- TODO: place your custom dungeon object definitions here

defineObject{
   name = "dungeon_breakable_wall",
   baseObject = "base_obstacle",
   components = {
      {
         class = "Model",
         model = "mod_assets/models/sx_dungeon_breakable_wall_hard.fbx",
      },
	   
       {
         class = "Obstacle",
         hitSound = "impact_blunt",
         hitEffect = "hit_dust",
      },
      {
         class = "Health",
         health = 15,
         spawnOnDeath = "dungeon_breakable_wall_damaged",
		 onDie = function(self)
               playSound("wall_breaking")
			   party.party:shakeCamera(0.02,2)
        end,
      },
      {
         class = "Controller",
      },
   },
   placement = "wall",
   automapTile = "wall",
   editorIcon = 120,
}

defineObject{
   name = "dungeon_breakable_wall_damaged",
   components = {
      {
         class = "Model",
         model = "mod_assets/models/sx_dungeon_breakable_wall_damaged.fbx",
      },
       {
         class = "Obstacle",
         hitSound = "impact_blunt",
         hitEffect = "hit_dust",
      },
      {
         class = "Health",
         health = 15,
         spawnOnDeath = "dungeon_breakable_wall_broken",
		 onDie = function(self)
               playSound("wall_breaking")
			   party.party:shakeCamera(0.02,2)
        end,
      },
      {
         class = "Controller",
      },
   },
   placement = "wall",
   automapTile = "grassy_ground",
   editorIcon = 120,
}

defineObject{
   name = "dungeon_breakable_wall_broken",
   components = {
      {
         class = "Model",
         model = "mod_assets/models/sx_dungeon_breakable_wall_broken.fbx",
      },  
       {
         class = "Controller",
      },
   },
   placement = "wall",
   editorIcon = 120,
}





















































