-- This file has been generated by Dungeon Editor 2.1.7

-- TODO: place your custom sound definitions here

defineSound{
	name = "wall_breaking",
	filename = "mod_assets/sounds/sx_wallbreaking.wav",
	loop = false,
	volume = 1.00,
	minDistance = 2,
	maxDistance = 2,
}
